"""create_scan_events_table

Revision ID: 10dd7550a7bd
Revises: 4f1d2b96b3a7
Create Date: 2026-03-01 18:39:50.203560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD
revision: str = '10dd7550a7bd'
down_revision: Union[str, None] = '4f1d2b96b3a7'
=======
revision: str = "10dd7550a7bd"
down_revision: Union[str, None] = "4f1d2b96b3a7"
>>>>>>> ahoyos
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
<<<<<<< HEAD
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('referrer', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_events_restaurant_id'), 'scan_events', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_events_restaurant_id'), table_name='scan_events')
    op.drop_table('scan_events')
    # ### end Alembic commands ###
=======
    op.create_table(
        "scan_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("restaurant_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("referrer", sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(["restaurant_id"], ["restaurants.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_events_restaurant_id"), "scan_events", ["restaurant_id"], unique=False)


def downgrade() -> None:
    op.drop_index(op.f("ix_scan_events_restaurant_id"), table_name="scan_events")
    op.drop_table("scan_events")
>>>>>>> ahoyos
