"""add_menu_interaction_events

Revision ID: e4f62cef6ee5
Revises: 10dd7550a7bd
Create Date: 2026-03-01 22:32:07.746556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4f62cef6ee5'
down_revision: Union[str, None] = '10dd7550a7bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_interaction_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_interaction_events_event_type'), 'menu_interaction_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_menu_interaction_events_restaurant_id'), 'menu_interaction_events', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_menu_interaction_events_session_id'), 'menu_interaction_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_interaction_events_session_id'), table_name='menu_interaction_events')
    op.drop_index(op.f('ix_menu_interaction_events_restaurant_id'), table_name='menu_interaction_events')
    op.drop_index(op.f('ix_menu_interaction_events_event_type'), table_name='menu_interaction_events')
    op.drop_table('menu_interaction_events')
    # ### end Alembic commands ###
